name: BUILD CICD-MINIO IMAGE

on: 
  push: 
    branches: [ main ]

env:
  VERSION: dev
  IMG: "minio-cicd"
  MINIO_ACCESS_KEY: minioadmin 
  MINIO_SECRET_KEY: minioadmin
  MINIO_BUCKET_NAME: ""
  MINIO_BUCKET_PUBLIC: False

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - 
        name: Checkout local
        uses: actions/checkout@v4
      -
        name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Build and export to Docker
        uses: docker/build-push-action@v5
        with:            
          context: .
          push: true
          tags: |
            ghcr.io/elri/${{ env.IMG }}:${{ env.VERSION }}
          build-args: |
            VERSION=${{ env.VERSION }}
            MINIO_ROOT_USER: ${{ env.MINIO_ACCESS_KEY }}
            MINIO_ROOT_PASSWORD: ${{ env.MINIO_SECRET_KEY }}
            MINIO_BUCKET_NAME: ${{ env.MINIO_BUCKET_NAME }}
            MINIO_BUCKET_PUBLIC: ${{ env.MINIO_BUCKET_PUBLIC }}